### ISSUE TITLE
in line 48 data = res['data'] KeyError: 'data'

### ISSUE THREAD

**Issue by Rlezzo** [zangxx66/jiwiki#1]
刚开始能用，突然就keyerror了，就不能再正常使用了

**Comment by zangxx66** [comment]
请提供一下不能正常使用的指令

**Comment by Rlezzo** [comment]
找到问题了，达到访问上限了以后，res里就没有'data'的字段了

**Comment by zangxx66** [comment]
更新了，添加了请求限制，一个IP在短时间内请求接口有一定限制，如果到上限了要等段时间才会恢复

**Comment by AAJk254** [comment]
Protocol -> panic on decoder MultiMsg.ApplyDown : runtime error: index out of range [0] with length 0
goroutine 56221 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1.1()
        github.com/Mrs4s/MiraiGo@v0.0.0-20211208080234-25c67a3ee1c1/client/network.go:326 +0x5d
panic({0x150d500, 0xc0001f4150})
        runtime/panic.go:1038 +0x215
github.com/Mrs4s/MiraiGo/client.decodeMultiApplyDownResponse.func1(0xc0000240f0, 0xc0002f5de0)
        github.com/Mrs4s/MiraiGo@v0.0.0-20211208080234-25c67a3ee1c1/client/multimsg.go:102 +0x105
github.com/Mrs4s/MiraiGo/client.decodeMultiApplyDownResponse(0xc0000240f0, 0x49, {0xc0000240f0, 0x49, 0x49})
        github.com/Mrs4s/MiraiGo@v0.0.0-20211208080234-25c67a3ee1c1/client/multimsg.go:103 +0x125
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0xc0004547d0)
        github.com/Mrs4s/MiraiGo@v0.0.0-20211208080234-25c67a3ee1c1/client/network.go:336 +0x1cb
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
        github.com/Mrs4s/MiraiGo@v0.0.0-20211208080234-25c67a3ee1c1/client/network.go:323 +0x6c5
使用命令后，后台报错
