### ISSUE TITLE
请求标头缺失参数导致的查询结果异常

### ISSUE THREAD

**Issue by soapspree** [zangxx66/jiwiki#2]
一个小修改，就不发pr了，开个issue讨论一下。
在我使用的过程中，查询出来的结果经常与小鸡词典网页查询出的结果不一致，并不是第一个最相关的结果。
举个例子，应该易于复现：小鸡词典网页查询`cdd`，抓到json中的第一个对象：

    "definitions": [{
	    "id": 958070346,
	    "term": {
		    "id": 500490530,
		    "title": "cdd",
		    "status": "processing"
	    },
	    #删掉了没用的 
        "plaintext": "cdd就是臭弟弟，是指喜欢很多个人的家伙（比如我），单推的反义词\n同时也是指《BanG Dream》里户山香澄以及她的声优寺川爱美，爱美曾经说过她喜欢这个组织的原因就是因为这里有很多女人（dd本d），同时又有了「女人都是爱美的」这句话",
    }]

查询结果是没问题的，`title`和`plaintext`都是第一个最相关的答案。换作插件进行查询，我log到的结果：

    'definitions': [{
	    'id': 855373574,
	    'term': {
		    'id': 335197138,
		    'title': 'cpdd',
		    'status': 'processing'
	    },
	    #删掉了没用的 
        'content': '“[链接:CP]滴”滴的首字母缩写，意为“找个人组CP，有意请联系我”。常用于玩网络游戏的00后之中。\n此处的CP即couple（配对），指组成一对，发展情侣关系的意思。也有人会特地     说明，找cp只为玩游戏，既不谈感情，也不发展线下关系。[划掉:其实就是找个异性][划掉,链接:开黑]\n“滴滴”则是指互相聊天发消息/打卡/加好友（可能是因为[链接:QQ]的消息提示音是滴滴声）。代表一切“联系我”的含义。\n\n经常出现在游戏公屏，在[链接:QQ飞车]和[链接:王者荣耀]中最为常见。',
    }],

可以看出用插件拿到的json顺序是乱的，第一个结果根本不是最相关的。对照浏览器发现是因为请求标头中缺失了`Client: web`这个参数，导致请求不完整，把这个加入到插件的header中就输出正常结果了。不过在浏览器中在上述参数下面还有一个叫`Client-Version: 2.6.10r`的参数，实测有没有也不影响输出，不过不太清楚会有什么影响。

**Comment by zangxx66** [comment]
感谢提醒
